// Code generated by goyacc -o yysmi.go -p smi smi.y. DO NOT EDIT.

//line smi.y:43

package smi

import __yyfmt__ "fmt"

//line smi.y:44

//line smi.y:57
type smiSymType struct {
	yys                  int
	text                 string
	id                   string
	err                  int
	date                 string
	objectPtr            string
	SmiStatus            int
	SmiAccess            int
	typePtr              string
	listPtr              string
	namedNumberPtr       string
	rangePtr             string
	valuePtr             string
	unsigned32           uint32
	integer32            int32
	unsigned64           uint64
	integer64            int64
	compl                string
	index                string
	modulePtr            string
	subjectCategoriesPtr string
	subid                SubID
	subidList            []SubID
	node                 Node
	nodeList             []Node
	idList               []string
	imp                  Import
	impList              []Import
}

const (
	tDOT_DOT            = 57346
	tCOLON_COLON_EQUAL  = 57347
	tOBJECT_IDENTIFIER  = 57348
	tNUMBER             = 57349
	tNEGATIVENUMBER     = 57350
	tNUMBER64           = 57351
	tNEGATIVENUMBER64   = 57352
	tBIN_STRING         = 57353
	tHEX_STRING         = 57354
	tQUOTED_STRING      = 57355
	tACCESS             = 57356
	tAGENT_CAPABILITIES = 57357
	tAPPLICATION        = 57358
	tAUGMENTS           = 57359
	tBEGIN_             = 57360
	tBITS               = 57361
	tCHOICE             = 57362
	tCONTACT_INFO       = 57363
	tCREATION_REQUIRES  = 57364
	tCOUNTER32          = 57365
	tCOUNTER64          = 57366
	tDEFINITIONS        = 57367
	tDEFVAL             = 57368
	tDESCRIPTION        = 57369
	tDISPLAY_HINT       = 57370
	tEND                = 57371
	tENTERPRISE         = 57372
	tEXPORTS            = 57373
	tEXTENDS            = 57374
	tFROM               = 57375
	tGROUP              = 57376
	tGAUGE32            = 57377
	tIDENTIFIER         = 57378
	tIMPLICIT           = 57379
	tIMPLIED            = 57380
	tIMPORTS            = 57381
	tINCLUDES           = 57382
	tINDEX              = 57383
	tINSTALL_ERRORS     = 57384
	tINTEGER            = 57385
	tINTEGER32          = 57386
	tINTEGER64          = 57387
	tIPADDRESS          = 57388
	tLAST_UPDATED       = 57389
	tMACRO              = 57390
	tMANDATORY_GROUPS   = 57391
	tMAX_ACCESS         = 57392
	tMIN_ACCESS         = 57393
	tMODULE             = 57394
	tMODULE_COMPLIANCE  = 57395
	tMODULE_IDENTITY    = 57396
	tNOT_ACCESSIBLE     = 57397
	tNOTIFICATIONS      = 57398
	tNOTIFICATION_GROUP = 57399
	tNOTIFICATION_TYPE  = 57400
	tOBJECT             = 57401
	tOBJECT_GROUP       = 57402
	tOBJECT_IDENTITY    = 57403
	tOBJECT_TYPE        = 57404
	tOBJECTS            = 57405
	tOCTET              = 57406
	tOF                 = 57407
	tORGANIZATION       = 57408
	tOPAQUE             = 57409
	tPIB_ACCESS         = 57410
	tPIB_DEFINITIONS    = 57411
	tPIB_INDEX          = 57412
	tPIB_MIN_ACCESS     = 57413
	tPIB_REFERENCES     = 57414
	tPIB_TAG            = 57415
	tPOLICY_ACCESS      = 57416
	tPRODUCT_RELEASE    = 57417
	tREFERENCE          = 57418
	tREVISION           = 57419
	tSEQUENCE           = 57420
	tSIZE               = 57421
	tSTATUS             = 57422
	tSTRING             = 57423
	tSUBJECT_CATEGORIES = 57424
	tSUPPORTS           = 57425
	tSYNTAX             = 57426
	tTEXTUAL_CONVENTION = 57427
	tTIMETICKS          = 57428
	tTRAP_TYPE          = 57429
	tUNIQUENESS         = 57430
	tUNITS              = 57431
	tUNIVERSAL          = 57432
	tUNSIGNED32         = 57433
	tUNSIGNED64         = 57434
	tVALUE              = 57435
	tVARIABLES          = 57436
	tVARIATION          = 57437
	tWRITE_SYNTAX       = 57438
)

var smiToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tDOT_DOT",
	"tCOLON_COLON_EQUAL",
	"tOBJECT_IDENTIFIER",
	"tNUMBER",
	"tNEGATIVENUMBER",
	"tNUMBER64",
	"tNEGATIVENUMBER64",
	"tBIN_STRING",
	"tHEX_STRING",
	"tQUOTED_STRING",
	"tACCESS",
	"tAGENT_CAPABILITIES",
	"tAPPLICATION",
	"tAUGMENTS",
	"tBEGIN_",
	"tBITS",
	"tCHOICE",
	"tCONTACT_INFO",
	"tCREATION_REQUIRES",
	"tCOUNTER32",
	"tCOUNTER64",
	"tDEFINITIONS",
	"tDEFVAL",
	"tDESCRIPTION",
	"tDISPLAY_HINT",
	"tEND",
	"tENTERPRISE",
	"tEXPORTS",
	"tEXTENDS",
	"tFROM",
	"tGROUP",
	"tGAUGE32",
	"tIDENTIFIER",
	"tIMPLICIT",
	"tIMPLIED",
	"tIMPORTS",
	"tINCLUDES",
	"tINDEX",
	"tINSTALL_ERRORS",
	"tINTEGER",
	"tINTEGER32",
	"tINTEGER64",
	"tIPADDRESS",
	"tLAST_UPDATED",
	"tMACRO",
	"tMANDATORY_GROUPS",
	"tMAX_ACCESS",
	"tMIN_ACCESS",
	"tMODULE",
	"tMODULE_COMPLIANCE",
	"tMODULE_IDENTITY",
	"tNOT_ACCESSIBLE",
	"tNOTIFICATIONS",
	"tNOTIFICATION_GROUP",
	"tNOTIFICATION_TYPE",
	"tOBJECT",
	"tOBJECT_GROUP",
	"tOBJECT_IDENTITY",
	"tOBJECT_TYPE",
	"tOBJECTS",
	"tOCTET",
	"tOF",
	"tORGANIZATION",
	"tOPAQUE",
	"tPIB_ACCESS",
	"tPIB_DEFINITIONS",
	"tPIB_INDEX",
	"tPIB_MIN_ACCESS",
	"tPIB_REFERENCES",
	"tPIB_TAG",
	"tPOLICY_ACCESS",
	"tPRODUCT_RELEASE",
	"tREFERENCE",
	"tREVISION",
	"tSEQUENCE",
	"tSIZE",
	"tSTATUS",
	"tSTRING",
	"tSUBJECT_CATEGORIES",
	"tSUPPORTS",
	"tSYNTAX",
	"tTEXTUAL_CONVENTION",
	"tTIMETICKS",
	"tTRAP_TYPE",
	"tUNIQUENESS",
	"tUNITS",
	"tUNIVERSAL",
	"tUNSIGNED32",
	"tUNSIGNED64",
	"tVALUE",
	"tVARIABLES",
	"tVARIATION",
	"tWRITE_SYNTAX",
	"'{'",
	"'}'",
	"';'",
	"','",
	"'('",
	"')'",
	"'['",
	"']'",
	"'.'",
	"'|'",
}

var smiStatenames = [...]string{}

const (
	smiEofCode          = 1
	smiErrCode          = 2
	smiInitialStackSize = 16
)

//line smi.y:1929

//line yacctab:1
var smiExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 27,
	29, 51,
	-2, 0,
	-1, 32,
	29, 50,
	-2, 0,
	-1, 49,
	5, 86,
	15, 372,
	53, 337,
	57, 333,
	60, 329,
	-2, 82,
	-1, 155,
	97, 188,
	101, 186,
	-2, 185,
	-1, 156,
	101, 191,
	-2, 190,
	-1, 157,
	97, 193,
	105, 49,
	-2, 107,
	-1, 166,
	101, 223,
	-2, 222,
	-1, 190,
	105, 49,
	-2, 193,
	-1, 199,
	101, 199,
	-2, 198,
}

const smiPrivate = 57344

const smiLast = 780

var smiAct = [...]int{
	279, 672, 445, 561, 615, 588, 639, 351, 609, 229,
	626, 592, 580, 143, 582, 557, 524, 444, 12, 533,
	499, 477, 230, 466, 345, 363, 421, 174, 362, 274,
	271, 256, 255, 253, 246, 226, 234, 227, 149, 79,
	205, 206, 152, 208, 158, 4, 157, 4, 198, 412,
	308, 659, 207, 309, 309, 317, 316, 586, 437, 147,
	148, 436, 435, 164, 169, 401, 605, 599, 600, 601,
	602, 603, 604, 606, 209, 165, 157, 26, 197, 675,
	648, 676, 124, 155, 156, 170, 163, 550, 618, 147,
	619, 122, 388, 164, 169, 611, 572, 612, 573, 160,
	548, 439, 549, 440, 159, 165, 405, 168, 406, 403,
	369, 292, 647, 155, 156, 170, 163, 339, 162, 340,
	318, 216, 319, 106, 310, 144, 167, 296, 305, 160,
	306, 166, 171, 291, 159, 292, 630, 168, 211, 197,
	21, 295, 644, 161, 176, 643, 642, 203, 162, 125,
	629, 621, 585, 584, 574, 566, 167, 597, 640, 551,
	530, 166, 171, 529, 528, 141, 474, 473, 669, 140,
	459, 455, 342, 161, 294, 248, 109, 19, 594, 204,
	578, 228, 577, 575, 564, 547, 545, 539, 538, 189,
	521, 507, 506, 494, 493, 492, 446, 443, 426, 195,
	423, 391, 300, 298, 209, 225, 210, 212, 214, 220,
	196, 217, 218, 219, 187, 180, 178, 8, 616, 344,
	224, 215, 201, 543, 128, 289, 589, 486, 130, 500,
	277, 278, 195, 249, 134, 251, 250, 379, 252, 199,
	424, 265, 302, 196, 366, 304, 268, 258, 257, 260,
	259, 262, 261, 303, 299, 276, 297, 240, 177, 129,
	323, 254, 478, 346, 241, 395, 285, 633, 301, 348,
	504, 77, 237, 322, 293, 116, 132, 331, 336, 115,
	10, 536, 113, 114, 135, 505, 111, 634, 136, 332,
	239, 353, 137, 467, 355, 228, 202, 326, 327, 337,
	330, 228, 284, 471, 139, 313, 537, 312, 513, 179,
	364, 519, 560, 329, 29, 374, 314, 315, 328, 254,
	288, 335, 373, 503, 11, 358, 287, 360, 17, 16,
	354, 367, 356, 380, 359, 200, 127, 25, 221, 242,
	334, 368, 370, 372, 371, 333, 338, 393, 123, 190,
	375, 15, 33, 107, 244, 674, 650, 397, 398, 587,
	581, 527, 457, 447, 376, 433, 407, 377, 378, 410,
	387, 381, 382, 383, 384, 385, 404, 386, 399, 48,
	402, 390, 365, 290, 48, 108, 155, 156, 222, 562,
	665, 419, 400, 22, 422, 258, 257, 260, 259, 262,
	261, 428, 160, 429, 138, 430, 663, 159, 14, 280,
	231, 434, 416, 417, 418, 656, 364, 17, 16, 569,
	413, 414, 20, 646, 628, 627, 628, 453, 411, 357,
	267, 266, 23, 441, 451, 431, 667, 655, 352, 525,
	517, 484, 175, 422, 409, 275, 458, 272, 461, 247,
	235, 269, 442, 263, 5, 576, 364, 450, 472, 514,
	489, 481, 480, 479, 438, 427, 392, 454, 172, 126,
	18, 311, 460, 462, 463, 3, 670, 469, 6, 658,
	540, 468, 184, 120, 555, 554, 495, 432, 183, 482,
	119, 449, 182, 485, 496, 487, 118, 448, 490, 181,
	501, 491, 509, 510, 511, 117, 508, 544, 522, 520,
	341, 213, 264, 194, 193, 192, 191, 526, 350, 515,
	349, 488, 563, 425, 396, 286, 173, 541, 552, 112,
	307, 452, 186, 110, 188, 185, 121, 30, 9, 546,
	470, 523, 542, 607, 608, 233, 232, 133, 558, 559,
	394, 347, 553, 671, 664, 666, 662, 638, 571, 637,
	591, 516, 498, 565, 570, 567, 568, 583, 497, 44,
	632, 635, 535, 534, 532, 531, 556, 512, 483, 465,
	464, 610, 41, 558, 583, 593, 43, 42, 614, 590,
	624, 622, 13, 361, 238, 236, 613, 620, 131, 476,
	475, 625, 623, 617, 595, 579, 518, 502, 223, 243,
	408, 415, 273, 325, 154, 583, 324, 598, 596, 321,
	146, 142, 34, 40, 39, 631, 283, 281, 282, 593,
	636, 641, 389, 610, 420, 645, 343, 456, 38, 649,
	37, 651, 652, 654, 80, 653, 36, 245, 320, 270,
	153, 657, 151, 97, 35, 150, 52, 84, 63, 64,
	51, 98, 99, 47, 660, 661, 145, 50, 668, 45,
	24, 32, 673, 100, 31, 677, 76, 75, 678, 673,
	28, 27, 85, 104, 86, 83, 82, 87, 81, 46,
	78, 88, 89, 49, 7, 101, 102, 2, 90, 91,
	92, 1, 62, 0, 0, 93, 0, 0, 0, 0,
	72, 74, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 73, 94, 95, 103, 0, 0, 0, 96,
	105, 70, 65, 67, 0, 0, 0, 0, 0, 0,
	61, 53, 0, 0, 60, 56, 0, 59, 57, 54,
	0, 0, 0, 0, 69, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 58, 68, 55, 0, 0, 0, 71, 66,
}

var smiPact = [...]int{
	448, -1000, 448, -1000, 120, -1000, -1000, 255, 411, 465,
	-1000, -1000, 79, 411, -1000, -1000, -1000, 39, 375, -1000,
	-1000, 425, 306, -25, 275, -1000, -1000, 687, -1000, 638,
	24, 324, 687, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 78, -1000, 227, 221,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -8, 638, -1000, 49, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	464, 300, 137, 179, 144, 213, 152, 224, 231, 239,
	389, 256, -1000, -1000, 448, 638, 40, 463, -1000, 436,
	70, 178, 119, 262, 118, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 117, -1000, -1000,
	343, -1000, -1000, -1000, -1000, -1000, -1000, 38, -57, 158,
	299, 206, 82, -23, 37, 37, -1000, -23, 20, 37,
	37, 37, 112, 308, 361, -1000, 131, 436, 411, 397,
	444, 209, 234, 177, 189, 310, 326, 443, 77, -1000,
	38, 37, 107, 37, 107, -1000, -1000, 240, 447, -1000,
	-23, 424, 423, 445, 441, -1000, -1000, -1000, -1000, 439,
	-1000, 388, -1000, 37, -1000, -1000, 182, -1000, -1000, -1000,
	411, 411, 396, 252, 396, 356, 35, -1000, -1000, -1000,
	208, -1000, 76, 41, -1000, 26, 176, 106, 174, 105,
	436, 396, -1000, 173, 396, 30, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -52, 23, -1000, 467, -1000, -1000, -1000,
	-1000, -1000, -1000, -23, 20, -1000, -48, -49, -1000, -1000,
	22, -1000, 254, 19, -1000, -1000, -1000, 74, 125, 187,
	-1000, 197, -1000, -1000, -1000, -1000, 432, -1000, -1000, -1000,
	396, -1000, 411, 396, -1000, 444, 422, 436, 411, 436,
	411, 355, 164, 436, -1000, -1000, 443, 9, -1000, 388,
	388, 388, -1000, -1000, -1000, -1000, 285, 278, -1000, 441,
	-1000, -1000, -1000, -23, -1000, -1000, -23, -23, 156, 297,
	-23, -23, -23, -23, -23, -1000, -23, -1000, -1000, -1000,
	439, -9, -1000, 354, 104, 461, 396, 192, -1000, 432,
	432, -1000, -1000, 187, -1000, 371, -1000, -37, 353, 11,
	349, 8, -1000, -1000, -1000, 396, 438, 342, -1000, 421,
	-1000, -53, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -23,
	-23, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 405, 187,
	396, 411, 103, -1000, 160, -1000, 101, -1000, -1000, 460,
	396, -1000, 396, -1000, 396, -1000, 411, -1000, 338, -1000,
	396, -40, -41, -1000, -1000, -44, -1000, -1000, 459, -1000,
	3, -1000, -1000, 411, 436, 100, 411, 99, 336, -1000,
	-1000, -1000, 187, 396, -1000, -1000, -1000, -1000, 420, -1000,
	411, 73, 335, 411, 72, -1000, 411, 396, 187, 187,
	241, -1000, 187, -1000, -1000, -1000, 261, 396, 69, -1000,
	68, 185, 458, 457, 456, 241, -1000, 435, 187, 143,
	187, -1000, -1000, -1000, -1000, 455, 185, -1000, 397, 98,
	97, 96, -1000, -1000, 411, 146, 70, 253, 95, 94,
	-1000, -1000, 411, 411, 411, 259, -1000, 454, 146, -1000,
	434, -1000, 270, -1000, 93, -1000, 433, 411, 334, 66,
	65, 62, 247, 91, 90, -1000, -1000, 411, 135, -1000,
	89, 411, 88, 2, -1000, -14, 61, 396, -1000, -1000,
	-1000, -1000, 247, -1000, -1000, -1000, -1000, -1000, 411, 411,
	272, -1000, 363, -1000, 87, 411, 57, 411, -1000, 433,
	412, -1000, -1000, -1000, 411, 411, -2, -1000, -1000, 56,
	86, 450, 85, 83, 322, 55, -1000, 54, -1000, -45,
	332, 142, -1000, 411, -1000, 411, 81, 60, 411, -3,
	-1000, 411, -1000, -1000, -1000, -1000, -1000, 396, 122, 70,
	-1000, -10, -1000, -1000, 411, 53, -1000, 419, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 52, 36, -1000,
	-1000, -1000, 322, -1000, -1000, 216, 70, -1000, 63, 411,
	48, -1000, 47, 44, 417, 12, -1000, -21, -1000, -1000,
	411, -1000, 329, 432, 432, -1000, -1000, -1000, 63, -1000,
	411, -1000, -1000, -1000, -1000, -1000, -21, 431, 408, -1000,
	396, -1000, -1000, -1000, -1000, -1000, -51, -1000, 142, -1000,
	122, 392, 368, 430, 363, 71, -1000, -1000, -1000, 411,
	328, -19, -1000, -1000, 396, -1000, 411, -1000, -1000,
}

var smiPgo = [...]int{
	0, 701, 697, 475, 694, 44, 39, 690, 688, 686,
	685, 681, 680, 677, 676, 271, 674, 671, 352, 670,
	669, 667, 666, 663, 660, 659, 658, 656, 655, 351,
	654, 652, 42, 650, 649, 30, 13, 648, 647, 34,
	646, 640, 638, 637, 636, 634, 26, 632, 628, 627,
	626, 624, 623, 622, 621, 620, 619, 618, 38, 617,
	616, 614, 613, 40, 41, 52, 33, 32, 31, 43,
	612, 29, 611, 27, 610, 609, 608, 7, 607, 606,
	605, 12, 14, 17, 3, 604, 602, 601, 2, 25,
	24, 600, 599, 21, 598, 595, 35, 37, 594, 593,
	28, 0, 22, 9, 592, 408, 591, 590, 10, 587,
	586, 582, 580, 579, 23, 578, 577, 576, 15, 575,
	574, 19, 573, 572, 5, 4, 571, 570, 569, 568,
	562, 20, 561, 560, 11, 559, 557, 6, 556, 555,
	554, 553, 1, 551, 550, 547, 546, 545, 36, 8,
	544, 543, 542, 16, 541, 540, 538, 537, 536, 535,
	534, 533, 532, 531, 530, 529, 526, 525, 524, 523,
	522, 521, 520, 518, 516, 515, 514, 513, 512, 511,
	510, 509, 508, 507, 506, 505, 499, 497, 496, 492,
	491, 490, 488, 487, 486, 485, 484, 483, 482, 481,
	480, 479, 476,
}

var smiR1 = [...]int{
	0, 1, 1, 2, 2, 3, 4, 4, 156, 156,
	11, 11, 12, 19, 157, 19, 13, 13, 14, 14,
	15, 7, 7, 6, 6, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	9, 9, 9, 9, 9, 9, 9, 10, 10, 5,
	16, 16, 17, 17, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 158, 159, 20,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	160, 22, 29, 30, 161, 53, 23, 23, 23, 24,
	24, 26, 26, 26, 26, 26, 25, 25, 25, 27,
	27, 54, 162, 163, 54, 54, 31, 32, 33, 34,
	34, 35, 36, 36, 37, 37, 37, 38, 38, 164,
	39, 40, 41, 43, 43, 165, 166, 42, 44, 44,
	45, 45, 46, 47, 47, 49, 49, 49, 50, 167,
	167, 168, 143, 143, 169, 144, 144, 170, 152, 152,
	151, 151, 150, 150, 149, 171, 155, 155, 154, 154,
	153, 172, 48, 173, 48, 51, 52, 145, 145, 146,
	147, 147, 148, 148, 55, 55, 55, 55, 55, 55,
	28, 28, 56, 56, 57, 58, 174, 58, 175, 58,
	58, 176, 58, 177, 58, 58, 58, 58, 58, 178,
	58, 58, 58, 58, 59, 59, 59, 59, 59, 59,
	59, 59, 59, 60, 60, 60, 60, 61, 61, 61,
	61, 61, 61, 179, 61, 61, 61, 61, 61, 61,
	61, 61, 61, 61, 62, 62, 62, 62, 62, 62,
	62, 62, 62, 63, 63, 63, 63, 64, 65, 66,
	66, 67, 67, 68, 68, 68, 68, 68, 68, 69,
	70, 70, 180, 71, 72, 72, 73, 74, 75, 75,
	76, 76, 77, 181, 78, 78, 182, 78, 78, 183,
	79, 79, 80, 80, 81, 81, 82, 83, 84, 84,
	85, 85, 86, 86, 87, 87, 88, 89, 90, 90,
	91, 91, 92, 92, 184, 93, 94, 94, 95, 96,
	96, 97, 98, 99, 99, 100, 101, 102, 103, 104,
	104, 105, 105, 105, 106, 107, 107, 108, 108, 185,
	186, 187, 109, 188, 189, 190, 110, 191, 192, 193,
	111, 112, 113, 113, 194, 114, 115, 115, 115, 116,
	116, 117, 117, 118, 119, 119, 120, 120, 121, 121,
	195, 122, 196, 123, 124, 124, 125, 125, 126, 127,
	127, 127, 197, 198, 199, 128, 129, 129, 130, 130,
	200, 131, 133, 133, 134, 132, 132, 135, 135, 136,
	136, 201, 202, 137, 138, 138, 139, 140, 140, 141,
	141, 142,
}

var smiR2 = [...]int{
	0, 1, 0, 1, 2, 9, 3, 0, 1, 1,
	1, 0, 3, 0, 0, 3, 1, 0, 1, 2,
	3, 1, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 0, 0, 5,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	0, 3, 1, 7, 0, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 0, 11, 1, 3, 1, 4, 1,
	3, 2, 1, 4, 1, 1, 2, 1, 3, 0,
	5, 11, 21, 0, 2, 0, 0, 11, 4, 0,
	1, 3, 1, 2, 0, 1, 1, 0, 2, 1,
	1, 0, 5, 0, 0, 5, 0, 0, 5, 0,
	1, 0, 1, 3, 1, 0, 5, 0, 1, 3,
	4, 0, 3, 0, 3, 12, 16, 4, 0, 1,
	1, 3, 1, 4, 1, 2, 1, 1, 1, 1,
	5, 5, 1, 1, 1, 1, 0, 3, 0, 3,
	1, 0, 3, 0, 3, 4, 2, 4, 2, 0,
	4, 2, 4, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 2, 2, 3, 3, 2, 1, 2,
	1, 2, 1, 0, 3, 2, 1, 2, 1, 2,
	1, 2, 1, 2, 2, 2, 2, 2, 2, 1,
	2, 1, 1, 1, 1, 1, 0, 3, 6, 1,
	3, 1, 3, 1, 1, 1, 1, 1, 1, 3,
	1, 3, 0, 5, 1, 1, 1, 1, 2, 0,
	2, 0, 1, 0, 5, 4, 0, 5, 0, 0,
	5, 0, 1, 3, 2, 1, 1, 1, 4, 0,
	1, 3, 1, 0, 1, 3, 1, 1, 2, 0,
	1, 0, 1, 2, 0, 5, 4, 0, 4, 1,
	3, 1, 4, 1, 3, 1, 1, 1, 1, 1,
	2, 1, 1, 4, 1, 1, 2, 4, 1, 0,
	0, 0, 15, 0, 0, 0, 15, 0, 0, 0,
	15, 1, 1, 2, 0, 5, 2, 1, 0, 4,
	0, 1, 3, 1, 1, 0, 1, 2, 1, 1,
	0, 5, 0, 8, 2, 0, 2, 0, 1, 2,
	2, 0, 0, 0, 0, 17, 1, 0, 1, 2,
	0, 8, 1, 3, 1, 2, 1, 1, 0, 1,
	2, 0, 0, 11, 2, 0, 1, 4, 0, 1,
	3, 1,
}

var smiChk = [...]int{
	-1000, -1, -2, -3, -5, 6, -3, -4, 97, -156,
	25, 69, -103, -104, -105, -29, 7, 6, 5, 98,
	-105, 101, 18, 7, -19, 31, 102, -11, -12, 39,
	-157, -16, -17, -18, -53, -30, -40, -41, -42, -51,
	-52, -111, -109, -110, -128, -20, 2, -23, -29, 6,
	-21, -24, -27, 54, 62, 87, 58, 61, 85, 60,
	57, 53, 15, -26, -25, 45, 92, 46, 86, 67,
	44, 91, 23, 35, 24, -13, -14, -15, -7, -6,
	6, -8, -9, -10, 19, 44, 46, 49, 53, 54,
	60, 61, 62, 67, 85, 86, 91, 15, 23, 24,
	35, 57, 58, 87, 45, 92, 99, 29, -18, 98,
	-161, 59, -165, 61, 62, 58, 54, -185, -188, -191,
	-197, -158, 99, -15, 33, 100, 5, 36, 87, 80,
	84, -94, 63, -145, 82, 60, 57, 53, 15, 48,
	-5, -6, -54, -36, 85, -22, -55, 19, 20, -58,
	-28, -31, -32, -33, -61, 43, 44, 6, -5, 64,
	59, 103, 78, 46, 23, 35, 91, 86, 67, 24,
	45, 92, 5, -166, -73, 6, -36, 80, 97, 47,
	97, -186, -189, -192, -198, -159, -162, 97, -160, -58,
	6, -174, -175, -176, -177, -64, -65, 101, 105, 81,
	36, 16, 90, 65, 97, -63, -64, -65, -69, 97,
	-64, 101, -64, -179, -63, -65, 101, -64, -64, -64,
	97, 30, 27, -76, 89, -73, -96, -97, -88, -103,
	-102, 13, -146, -147, -148, 6, -95, 63, -98, 56,
	80, 75, 29, -75, 28, -38, -39, 6, 98, -64,
	-69, -64, -69, -66, 79, -67, -68, 8, 7, 10,
	9, 12, 11, 6, -178, -63, 7, 7, -32, 6,
	-34, -35, 6, -70, -71, 6, -64, -103, -103, -101,
	13, -49, -48, -50, 50, 14, -167, 74, 68, -101,
	27, 98, 100, 66, 98, 100, 101, 80, 97, 80,
	97, -73, -101, 80, -101, 98, 100, -164, 102, 106,
	101, 4, -69, -64, -65, -65, 104, 104, 98, 100,
	-37, -56, 19, 6, -60, -62, 43, 44, 64, 59,
	46, 23, 35, 91, 86, 67, 24, 45, 92, 98,
	100, -180, 98, -44, 94, -90, 76, -143, 72, -172,
	-173, -77, 6, -101, -97, -101, -148, 7, -73, -96,
	-73, -99, -100, -89, -103, 27, 80, -73, -39, 101,
	-67, -66, -68, 37, 37, -35, -63, -63, -63, 81,
	36, -63, -63, -63, -63, -63, -63, -71, 101, -47,
	27, 97, 5, -101, -144, 73, -168, -77, -77, -90,
	21, 102, 27, 98, 27, 98, 100, -101, -74, 6,
	27, 7, 102, -63, -63, -72, 7, 8, -90, -101,
	-45, -46, -88, 97, 80, -169, 97, 5, -101, -101,
	-101, -100, -193, 27, -101, 102, 102, 102, 5, 98,
	100, -103, -73, 97, -83, -88, 97, 27, -187, -190,
	-90, -101, -163, 7, -46, 98, -43, 27, -88, 98,
	-89, -101, -90, -90, -112, -113, -114, 52, -199, -90,
	-155, 42, -101, 98, 98, -91, -92, -93, 77, 5,
	5, 5, -114, -115, 6, -90, 84, -90, -171, 5,
	-93, -102, 97, 97, 97, -194, -103, -129, -130, -131,
	83, -36, -78, 70, 17, 32, 97, 97, -184, -103,
	-103, -103, -116, 49, 5, -131, -132, 6, -79, 41,
	-181, 97, -182, -154, -153, 6, -103, 27, 98, 98,
	98, -119, -120, -121, -122, -123, 34, 59, 97, 97,
	-200, -103, -152, 88, -183, 97, -83, 97, 98, 100,
	101, 98, -101, -121, -195, -196, -117, -118, -103, -103,
	40, -84, 26, -170, 97, -83, 98, -83, -153, 7,
	-103, -88, 98, 100, 98, 97, 5, 97, 97, -80,
	-81, 38, -82, -88, 98, 98, 102, 27, -124, 84,
	-118, -133, -134, -103, 97, -85, -57, 97, -59, 7,
	8, 9, 10, 11, 12, 6, 13, -151, -150, -149,
	-88, 98, 100, -82, -101, -125, 96, -36, 98, 100,
	-88, 98, -106, -86, -107, -87, -108, 6, 7, 98,
	100, -81, -127, 51, 71, -126, -36, -135, -136, -137,
	95, -134, 98, 98, 98, -108, 6, 100, 101, -149,
	27, -77, -77, -137, -88, 6, 7, -101, -201, 102,
	-124, -125, -138, 14, -140, 22, -139, 6, -84, 97,
	-202, -141, -142, -88, 27, 98, 100, -101, -142,
}

var smiDef = [...]int{
	2, -2, 1, 3, 7, 49, 4, 0, 0, 0,
	8, 9, 0, 318, 319, 321, 322, 82, 0, 6,
	320, 0, 13, 0, 11, 14, 323, -2, 10, 17,
	0, 0, -2, 52, 54, 55, 56, 57, 58, 59,
	60, 61, 62, 63, 64, 65, 0, 84, 125, -2,
	67, 87, 88, 70, 71, 72, 73, 74, 75, 76,
	77, 78, 79, 89, 90, 99, 100, 91, 92, 93,
	94, 95, 96, 97, 98, 0, 16, 18, 0, 21,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
	43, 44, 45, 46, 47, 48, 15, 5, 53, 66,
	0, 0, 0, 0, 0, 307, 168, 0, 0, 0,
	0, 0, 12, 19, 0, 0, 0, 0, 126, 0,
	0, 0, 0, 0, 0, 330, 334, 338, 373, 68,
	20, 22, 85, 101, 102, 105, 112, 0, 80, 174,
	0, 176, 177, 178, 179, -2, -2, -2, 0, 0,
	0, 0, 0, 246, 218, 220, -2, 246, 226, 228,
	230, 232, 0, 0, 0, 266, 271, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 269, 0, 0, 175,
	-2, 0, 0, 0, 0, 196, 201, 0, 0, -2,
	246, 0, 0, 0, 0, 217, 243, 244, 245, 0,
	219, 0, 221, 0, 225, 227, 0, 229, 231, 233,
	0, 0, 0, 137, 0, 0, 0, 309, 311, 296,
	0, 317, 0, 169, 170, 172, 0, 0, 0, 0,
	0, 0, 69, 0, 0, 0, 117, 119, 81, 187,
	189, 192, 194, 0, 0, 249, 251, 253, 254, 255,
	256, 257, 258, 0, 0, 203, 0, 0, 106, 107,
	0, 109, 0, 0, 260, 262, 224, 0, 129, 299,
	316, 143, 135, 136, 161, 163, 0, 139, 140, 270,
	0, 306, 0, 0, 167, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 268, 113, 0, 0, 247, 0,
	0, 0, 195, 197, 202, 200, 0, 0, 108, 0,
	111, 114, 115, 246, 182, 183, 246, 246, 0, 0,
	246, 246, 246, 246, 246, 239, 246, 241, 242, 259,
	0, 0, 83, 134, 0, 0, 0, 146, 141, 0,
	0, 138, 272, 299, 310, 0, 171, 0, 0, 0,
	0, 0, 313, 315, 297, 0, 0, 0, 118, 0,
	250, 0, 252, 180, 181, 110, 116, 213, 214, 246,
	246, 234, 235, 236, 237, 238, 240, 261, 0, 299,
	0, 0, 0, 298, 0, 144, 0, 162, 164, 0,
	0, 173, 0, 308, 0, 312, 0, 339, 0, 267,
	0, 0, 0, 215, 216, 0, 264, 265, 0, 133,
	0, 130, 132, 0, 0, 0, 0, 0, 0, 331,
	335, 314, 299, 0, 103, 120, 248, 263, 0, 128,
	0, 0, 123, 0, 0, 287, 0, 0, 299, 299,
	0, 374, 299, 127, 131, 121, 157, 0, 0, 142,
	0, 301, 0, 0, 0, 341, 342, 348, 299, 0,
	299, 155, 124, 145, 165, 0, 300, 302, 0, 0,
	0, 0, 343, 344, 347, 377, 0, 278, 0, 0,
	303, 304, 0, 0, 0, 350, 346, 0, 376, 378,
	0, 104, 281, 273, 0, 276, 0, 0, 0, 0,
	0, 0, 355, 0, 0, 379, 380, 386, 149, 279,
	0, 0, 0, 0, 158, 0, 0, 0, 332, 336,
	340, 345, 354, 356, 358, 359, 360, 362, 0, 0,
	0, 385, 289, 147, 0, 0, 0, 0, 156, 0,
	0, 166, 305, 357, 0, 0, 0, 351, 353, 0,
	0, 0, 0, 0, 0, 0, 275, 0, 159, 0,
	0, 365, 349, 0, 375, 0, 0, 0, 151, 0,
	282, 0, 285, 286, 274, 277, 160, 0, 367, 0,
	352, 0, 382, 384, 0, 0, 290, 293, 184, 204,
	205, 206, 207, 208, 209, 210, 211, 0, 150, 152,
	154, 280, 0, 284, 361, 371, 0, 364, 388, 0,
	0, 288, 0, 0, 324, 292, 325, 294, 328, 148,
	0, 283, 0, 0, 0, 366, 368, 381, 387, 389,
	0, 383, 122, 212, 291, 326, 0, 0, 0, 153,
	0, 369, 370, 390, 391, 295, 0, 363, 365, 327,
	367, 395, 398, 0, 289, 0, 394, 396, 392, 0,
	0, 0, 399, 401, 0, 397, 0, 393, 400,
}

var smiTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	101, 102, 3, 3, 100, 3, 105, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 99,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 103, 3, 104, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 97, 106, 98,
}

var smiTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96,
}

var smiTok3 = [...]int{
	0,
}

var smiErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	smiDebug        = 0
	smiErrorVerbose = false
)

type smiLexer interface {
	Lex(lval *smiSymType) int
	Error(s string)
}

type smiParser interface {
	Parse(smiLexer) int
	Lookahead() int
}

type smiParserImpl struct {
	lval  smiSymType
	stack [smiInitialStackSize]smiSymType
	char  int
}

func (p *smiParserImpl) Lookahead() int {
	return p.char
}

func smiNewParser() smiParser {
	return &smiParserImpl{}
}

const smiFlag = -1000

func smiTokname(c int) string {
	if c >= 1 && c-1 < len(smiToknames) {
		if smiToknames[c-1] != "" {
			return smiToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func smiStatname(s int) string {
	if s >= 0 && s < len(smiStatenames) {
		if smiStatenames[s] != "" {
			return smiStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func smiErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !smiErrorVerbose {
		return "syntax error"
	}

	for _, e := range smiErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + smiTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := smiPact[state]
	for tok := TOKSTART; tok-1 < len(smiToknames); tok++ {
		if n := base + tok; n >= 0 && n < smiLast && smiChk[smiAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if smiDef[state] == -2 {
		i := 0
		for smiExca[i] != -1 || smiExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; smiExca[i] >= 0; i += 2 {
			tok := smiExca[i]
			if tok < TOKSTART || smiExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if smiExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += smiTokname(tok)
	}
	return res
}

func smilex1(lex smiLexer, lval *smiSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = smiTok1[0]
		goto out
	}
	if char < len(smiTok1) {
		token = smiTok1[char]
		goto out
	}
	if char >= smiPrivate {
		if char < smiPrivate+len(smiTok2) {
			token = smiTok2[char-smiPrivate]
			goto out
		}
	}
	for i := 0; i < len(smiTok3); i += 2 {
		token = smiTok3[i+0]
		if token == char {
			token = smiTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = smiTok2[1] /* unknown char */
	}
	if smiDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", smiTokname(token), uint(char))
	}
	return char, token
}

func smiParse(smilex smiLexer) int {
	return smiNewParser().Parse(smilex)
}

func (smircvr *smiParserImpl) Parse(smilex smiLexer) int {
	var smin int
	var smiVAL smiSymType
	var smiDollar []smiSymType
	_ = smiDollar // silence set and not used
	smiS := smircvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	smistate := 0
	smircvr.char = -1
	smitoken := -1 // smircvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		smistate = -1
		smircvr.char = -1
		smitoken = -1
	}()
	smip := -1
	goto smistack

ret0:
	return 0

ret1:
	return 1

smistack:
	/* put a state and value onto the stack */
	if smiDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", smiTokname(smitoken), smiStatname(smistate))
	}

	smip++
	if smip >= len(smiS) {
		nyys := make([]smiSymType, len(smiS)*2)
		copy(nyys, smiS)
		smiS = nyys
	}
	smiS[smip] = smiVAL
	smiS[smip].yys = smistate

sminewstate:
	smin = smiPact[smistate]
	if smin <= smiFlag {
		goto smidefault /* simple state */
	}
	if smircvr.char < 0 {
		smircvr.char, smitoken = smilex1(smilex, &smircvr.lval)
	}
	smin += smitoken
	if smin < 0 || smin >= smiLast {
		goto smidefault
	}
	smin = smiAct[smin]
	if smiChk[smin] == smitoken { /* valid shift */
		smircvr.char = -1
		smitoken = -1
		smiVAL = smircvr.lval
		smistate = smin
		if Errflag > 0 {
			Errflag--
		}
		goto smistack
	}

smidefault:
	/* default state action */
	smin = smiDef[smistate]
	if smin == -2 {
		if smircvr.char < 0 {
			smircvr.char, smitoken = smilex1(smilex, &smircvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if smiExca[xi+0] == -1 && smiExca[xi+1] == smistate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			smin = smiExca[xi+0]
			if smin < 0 || smin == smitoken {
				break
			}
		}
		smin = smiExca[xi+1]
		if smin < 0 {
			goto ret0
		}
	}
	if smin == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			smilex.Error(smiErrorMessage(smistate, smitoken))
			Nerrs++
			if smiDebug >= 1 {
				__yyfmt__.Printf("%s", smiStatname(smistate))
				__yyfmt__.Printf(" saw %s\n", smiTokname(smitoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for smip >= 0 {
				smin = smiPact[smiS[smip].yys] + smiErrCode
				if smin >= 0 && smin < smiLast {
					smistate = smiAct[smin] /* simulate a shift of "error" */
					if smiChk[smistate] == smiErrCode {
						goto smistack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if smiDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", smiS[smip].yys)
				}
				smip--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if smiDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", smiTokname(smitoken))
			}
			if smitoken == smiEofCode {
				goto ret1
			}
			smircvr.char = -1
			smitoken = -1
			goto sminewstate /* try again in the same state */
		}
	}

	/* reduction by production smin */
	if smiDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", smin, smiStatname(smistate))
	}

	smint := smin
	smipt := smip
	_ = smipt // guard against "declared and not used"

	smip -= smiR2[smin]
	// smip is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if smip+1 >= len(smiS) {
		nyys := make([]smiSymType, len(smiS)*2)
		copy(nyys, smiS)
		smiS = nyys
	}
	smiVAL = smiS[smip+1]

	/* consult goto table to find next state */
	smin = smiR1[smin]
	smig := smiPgo[smin]
	smij := smig + smiS[smip].yys + 1

	if smij >= smiLast {
		smistate = smiAct[smig]
	} else {
		smistate = smiAct[smij]
		if smiChk[smistate] != -smin {
			smistate = smiAct[smig]
		}
	}
	// dummy call; replaced with literal code
	switch smint {

	case 2:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:358
		{
		}
	case 4:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:363
		{
		}
	case 5:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:378
		{
			m := Module{Name: smiDollar[1].id, Imports: smiDollar[7].impList, Nodes: smiDollar[8].nodeList}
			setModule(&smilex, &m)
		}
	case 6:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:385
		{
		}
	case 7:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:387
		{
		}
	case 8:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:391
		{
		}
	case 9:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:393
		{
		}
	case 11:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:401
		{
			smiVAL.impList = []Import{}
		}
	case 12:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:407
		{
			smiVAL.impList = smiDollar[2].impList
		}
	case 13:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:413
		{
		}
	case 14:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:415
		{
		}
	case 15:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:418
		{
		}
	case 17:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:423
		{
			smiVAL.impList = []Import{}
		}
	case 18:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:429
		{
			smiVAL.impList = []Import{smiDollar[1].imp}
		}
	case 19:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:433
		{
			smiVAL.impList = append(smiDollar[1].impList, smiDollar[2].imp)
		}
	case 20:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:441
		{
			smiVAL.imp = Import{From: smiDollar[3].id, Symbols: smiDollar[1].idList}
		}
	case 21:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:447
		{
			if smiDollar[1].id == "" {
				smiVAL.idList = []string{}
			} else {
				smiVAL.idList = []string{smiDollar[1].id}
			}
		}
	case 22:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:455
		{
			if smiDollar[3].id == "" {
				smiVAL.idList = smiDollar[1].idList
			} else {
				smiVAL.idList = append(smiDollar[1].idList, smiDollar[3].id)
			}
		}
	case 24:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:469
		{
			smiVAL.id = ""
		}
	case 25:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:479
		{
		}
	case 26:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:481
		{
		}
	case 50:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:518
		{
		}
	case 51:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:520
		{
		}
	case 52:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:524
		{
			if smiDollar[1].node.Type != NodeNotSupported {
				smiVAL.nodeList = []Node{smiDollar[1].node}
			} else {
				smiVAL.nodeList = []Node{}
			}
		}
	case 53:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:532
		{
			if smiDollar[2].node.Type != NodeNotSupported {
				smiVAL.nodeList = append(smiDollar[1].nodeList, smiDollar[2].node)
			}
		}
	case 54:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:540
		{
		}
	case 55:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:543
		{
		}
	case 56:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:546
		{
		}
	case 57:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:549
		{
		}
	case 58:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:552
		{
		}
	case 59:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:555
		{
		}
	case 60:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:558
		{
		}
	case 61:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:561
		{
		}
	case 62:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:564
		{
		}
	case 63:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:567
		{
		}
	case 64:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:570
		{
		}
	case 65:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:573
		{
		}
	case 66:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:576
		{
		}
	case 67:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:586
		{
		}
	case 68:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:589
		{
		}
	case 69:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:593
		{
		}
	case 70:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:597
		{
			smiVAL.id = smiDollar[1].id
		}
	case 71:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:598
		{
			smiVAL.id = smiDollar[1].id
		}
	case 72:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:599
		{
			smiVAL.id = smiDollar[1].id
		}
	case 73:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:600
		{
			smiVAL.id = smiDollar[1].id
		}
	case 74:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:601
		{
			smiVAL.id = smiDollar[1].id
		}
	case 75:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:602
		{
			smiVAL.id = smiDollar[1].id
		}
	case 76:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:603
		{
			smiVAL.id = smiDollar[1].id
		}
	case 77:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:604
		{
			smiVAL.id = smiDollar[1].id
		}
	case 78:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:605
		{
			smiVAL.id = smiDollar[1].id
		}
	case 79:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:606
		{
			smiVAL.id = smiDollar[1].id
		}
	case 80:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:610
		{
		}
	case 81:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:614
		{
		}
	case 82:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:622
		{
		}
	case 83:
		smiDollar = smiS[smipt-7 : smipt+1]
//line smi.y:629
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeObjectID, IDs: smiDollar[6].subidList}
		}
	case 84:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:638
		{
		}
	case 85:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:641
		{
		}
	case 86:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:646
		{
		}
	case 87:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:649
		{
		}
	case 88:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:652
		{
		}
	case 90:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:658
		{
		}
	case 101:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:679
		{
		}
	case 102:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:682
		{
		}
	case 103:
		smiDollar = smiS[smipt-7 : smipt+1]
//line smi.y:687
		{
		}
	case 104:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:691
		{
		}
	case 105:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:694
		{
		}
	case 106:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:700
		{
		}
	case 107:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:710
		{
		}
	case 108:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:716
		{
		}
	case 109:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:721
		{
		}
	case 110:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:724
		{
		}
	case 111:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:735
		{
		}
	case 112:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:740
		{
		}
	case 113:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:743
		{
		}
	case 114:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:749
		{
		}
	case 115:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:752
		{
		}
	case 116:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:755
		{
		}
	case 117:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:760
		{
		}
	case 118:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:763
		{
		}
	case 119:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:768
		{
		}
	case 120:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:771
		{
		}
	case 121:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:782
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeObjectID, IDs: smiDollar[10].subidList}
		}
	case 122:
		smiDollar = smiS[smipt-21 : smipt+1]
//line smi.y:803
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeObjectType, IDs: smiDollar[20].subidList, Description: smiDollar[11].text}
		}
	case 123:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:809
		{
		}
	case 124:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:812
		{
			smiVAL.text = smiDollar[2].text
		}
	case 125:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:818
		{
		}
	case 126:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:821
		{
		}
	case 127:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:828
		{
		}
	case 128:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:833
		{
		}
	case 129:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:836
		{
		}
	case 130:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:841
		{
		}
	case 131:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:844
		{
		}
	case 132:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:849
		{
		}
	case 133:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:854
		{
		}
	case 134:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:857
		{
		}
	case 135:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:861
		{
		}
	case 136:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:864
		{
		}
	case 137:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:867
		{
		}
	case 138:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:871
		{
		}
	case 139:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:875
		{
		}
	case 140:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:878
		{
		}
	case 141:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:882
		{
		}
	case 142:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:885
		{
		}
	case 143:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:887
		{
		}
	case 144:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:891
		{
		}
	case 145:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:894
		{
		}
	case 146:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:896
		{
		}
	case 147:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:901
		{
		}
	case 148:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:904
		{
		}
	case 149:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:906
		{
		}
	case 150:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:910
		{
		}
	case 151:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:912
		{
		}
	case 152:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:916
		{
		}
	case 153:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:919
		{
		}
	case 154:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:924
		{
		}
	case 155:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:928
		{
		}
	case 156:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:931
		{
		}
	case 157:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:933
		{
		}
	case 158:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:937
		{
		}
	case 159:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:940
		{
		}
	case 160:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:945
		{
		}
	case 161:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:951
		{
		}
	case 162:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:954
		{
		}
	case 163:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:956
		{
		}
	case 164:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:959
		{
		}
	case 165:
		smiDollar = smiS[smipt-12 : smipt+1]
//line smi.y:970
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeNotification, IDs: smiDollar[11].subidList}
		}
	case 166:
		smiDollar = smiS[smipt-16 : smipt+1]
//line smi.y:985
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeModuleID, IDs: smiDollar[15].subidList}
		}
	case 167:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:991
		{
		}
	case 168:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:994
		{
		}
	case 169:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:999
		{
		}
	case 170:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1004
		{
		}
	case 171:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1007
		{
		}
	case 172:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1012
		{
		}
	case 173:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1015
		{
		}
	case 174:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1020
		{
		}
	case 175:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1023
		{
		}
	case 176:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1026
		{
		}
	case 177:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1029
		{
		}
	case 178:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1032
		{
		}
	case 179:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1035
		{
		}
	case 180:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1040
		{
		}
	case 181:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1042
		{
		}
	case 182:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1050
		{
		}
	case 183:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1052
		{
		}
	case 184:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1057
		{
		}
	case 185:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1066
		{
		}
	case 186:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1069
		{
		}
	case 187:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1072
		{
		}
	case 188:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1075
		{
		}
	case 189:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1078
		{
		}
	case 190:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1081
		{
		}
	case 191:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1084
		{
		}
	case 192:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1087
		{
		}
	case 193:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1090
		{
		}
	case 194:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1093
		{
		}
	case 195:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1096
		{
		}
	case 196:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1099
		{
		}
	case 197:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1102
		{
		}
	case 198:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1105
		{
		}
	case 199:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1108
		{
		}
	case 200:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1111
		{
		}
	case 201:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1114
		{
		}
	case 202:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1117
		{
		}
	case 203:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1120
		{
		}
	case 204:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1126
		{
		}
	case 205:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1129
		{
		}
	case 206:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1132
		{
		}
	case 207:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1135
		{
		}
	case 208:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1138
		{
		}
	case 209:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1141
		{
		}
	case 210:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1144
		{
		}
	case 211:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1147
		{
		}
	case 212:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1166
		{
		}
	case 213:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1175
		{
		}
	case 214:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1178
		{
		}
	case 215:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1181
		{
		}
	case 216:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1184
		{
		}
	case 217:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1189
		{
		}
	case 218:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1192
		{
		}
	case 219:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1195
		{
		}
	case 220:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1198
		{
		}
	case 221:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1201
		{
		}
	case 222:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1204
		{
		}
	case 223:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1207
		{
		}
	case 224:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1210
		{
		}
	case 225:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1213
		{
		}
	case 226:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1216
		{
		}
	case 227:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1219
		{
		}
	case 228:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1222
		{
		}
	case 229:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1225
		{
		}
	case 230:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1228
		{
		}
	case 231:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1231
		{
		}
	case 232:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1234
		{
		}
	case 233:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1237
		{
		}
	case 234:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1246
		{
		}
	case 235:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1249
		{
		}
	case 236:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1252
		{
		}
	case 237:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1255
		{
		}
	case 238:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1258
		{
		}
	case 239:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1261
		{
		}
	case 240:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1264
		{
		}
	case 241:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1267
		{
		}
	case 242:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1270
		{
		}
	case 243:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1275
		{
		}
	case 244:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1278
		{
		}
	case 245:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1281
		{
		}
	case 246:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1284
		{
		}
	case 247:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1297
		{
		}
	case 248:
		smiDollar = smiS[smipt-6 : smipt+1]
//line smi.y:1307
		{
		}
	case 249:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1312
		{
		}
	case 250:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1315
		{
		}
	case 251:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1320
		{
		}
	case 252:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1323
		{
		}
	case 253:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1328
		{
		}
	case 254:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1331
		{
		}
	case 255:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1334
		{
		}
	case 256:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1337
		{
		}
	case 257:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1340
		{
		}
	case 258:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1343
		{
		}
	case 259:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1348
		{
		}
	case 260:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1353
		{
		}
	case 261:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1356
		{
		}
	case 262:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1361
		{
		}
	case 263:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1364
		{
		}
	case 264:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1369
		{
		}
	case 265:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1372
		{
		}
	case 266:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1377
		{
		}
	case 267:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1382
		{
		}
	case 268:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1387
		{
		}
	case 269:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1390
		{
		}
	case 270:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1395
		{
		}
	case 271:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1398
		{
		}
	case 272:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1403
		{
		}
	case 273:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1408
		{
		}
	case 274:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1411
		{
		}
	case 275:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1414
		{
		}
	case 276:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1417
		{
		}
	case 277:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1420
		{
		}
	case 278:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1423
		{
		}
	case 279:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1428
		{
		}
	case 280:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1431
		{
		}
	case 281:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1434
		{
		}
	case 282:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1439
		{
		}
	case 283:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1442
		{
		}
	case 284:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1447
		{
		}
	case 285:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1450
		{
		}
	case 286:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1455
		{
		}
	case 287:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1460
		{
		}
	case 288:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1465
		{
		}
	case 289:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1468
		{
		}
	case 290:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1472
		{
		}
	case 291:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1474
		{
		}
	case 292:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1479
		{
		}
	case 293:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1481
		{
		}
	case 294:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1485
		{
		}
	case 295:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1488
		{
		}
	case 296:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1493
		{
		}
	case 297:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1498
		{
		}
	case 298:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1503
		{
		}
	case 299:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1506
		{
		}
	case 300:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1510
		{
		}
	case 301:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1512
		{
		}
	case 302:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1516
		{
		}
	case 303:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1518
		{
		}
	case 304:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1522
		{
		}
	case 305:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1525
		{
		}
	case 306:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1530
		{
		}
	case 307:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1533
		{
		}
	case 308:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1538
		{
		}
	case 309:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1543
		{
		}
	case 310:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1546
		{
		}
	case 311:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1551
		{
		}
	case 312:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1556
		{
		}
	case 313:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1561
		{
		}
	case 314:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1564
		{
		}
	case 315:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1569
		{
		}
	case 316:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1574
		{
		}
	case 317:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1579
		{
		}
	case 318:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1584
		{
		}
	case 319:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1590
		{
			smiVAL.subidList = []SubID{smiDollar[1].subid}
		}
	case 320:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1595
		{
			smiVAL.subidList = append(smiDollar[1].subidList, smiDollar[2].subid)
		}
	case 321:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1603
		{
			smiVAL.subid = SubID{ID: -1, Label: smiDollar[1].id}
		}
	case 322:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1607
		{
			smiVAL.subid = SubID{ID: int(smiDollar[1].unsigned32)}
		}
	case 323:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1611
		{
			smiVAL.subid = SubID{int(smiDollar[3].unsigned32), smiDollar[1].id}
		}
	case 324:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1617
		{
		}
	case 325:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1621
		{
		}
	case 326:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1623
		{
		}
	case 327:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1627
		{
		}
	case 328:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1629
		{
		}
	case 329:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1633
		{
		}
	case 330:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1636
		{
		}
	case 331:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:1641
		{
		}
	case 332:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1645
		{
		}
	case 333:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1650
		{
		}
	case 334:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1653
		{
		}
	case 335:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:1658
		{
		}
	case 336:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1662
		{
		}
	case 337:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1667
		{
		}
	case 338:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1670
		{
		}
	case 339:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1674
		{
		}
	case 340:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1679
		{
		}
	case 341:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1684
		{
		}
	case 342:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1689
		{
		}
	case 343:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1692
		{
		}
	case 344:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1697
		{
		}
	case 345:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1701
		{
		}
	case 346:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1706
		{
		}
	case 347:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1709
		{
		}
	case 348:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1712
		{
		}
	case 349:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1717
		{
		}
	case 350:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1720
		{
		}
	case 351:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1725
		{
		}
	case 352:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1728
		{
		}
	case 353:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1733
		{
		}
	case 354:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1738
		{
		}
	case 355:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1741
		{
		}
	case 356:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1746
		{
		}
	case 357:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1749
		{
		}
	case 358:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1754
		{
		}
	case 359:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1757
		{
		}
	case 360:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1762
		{
		}
	case 361:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1766
		{
		}
	case 362:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1771
		{
		}
	case 363:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1778
		{
		}
	case 364:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1783
		{
		}
	case 365:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1786
		{
		}
	case 366:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1791
		{
		}
	case 367:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1794
		{
		}
	case 368:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1799
		{
		}
	case 369:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1804
		{
		}
	case 370:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1807
		{
		}
	case 371:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1810
		{
		}
	case 372:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1815
		{
		}
	case 373:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1818
		{
		}
	case 374:
		smiDollar = smiS[smipt-10 : smipt+1]
//line smi.y:1823
		{
		}
	case 375:
		smiDollar = smiS[smipt-17 : smipt+1]
//line smi.y:1828
		{
		}
	case 376:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1833
		{
		}
	case 377:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1835
		{
		}
	case 378:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1839
		{
		}
	case 379:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1841
		{
		}
	case 380:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1845
		{
		}
	case 381:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1849
		{
		}
	case 382:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1854
		{
		}
	case 383:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1857
		{
		}
	case 384:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1862
		{
		}
	case 385:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1867
		{
		}
	case 386:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1870
		{
		}
	case 387:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1875
		{
		}
	case 388:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1877
		{
		}
	case 389:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1881
		{
		}
	case 390:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1883
		{
		}
	case 391:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1887
		{
		}
	case 392:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1894
		{
		}
	case 393:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:1897
		{
		}
	case 394:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1902
		{
		}
	case 395:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1904
		{
		}
	case 396:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1908
		{
		}
	case 397:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1913
		{
		}
	case 398:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1916
		{
		}
	case 399:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1920
		{
		}
	case 400:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1922
		{
		}
	case 401:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1926
		{
		}
	}
	goto smistack /* stack new state and value */
}
